
version: '3.8'

x-common-variables: &common-variables
  DATABASE_NAME: testdb
  MONGO_USER:
  MONGO_PASSWORD: 

services: 
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: nest-backend
    ports: 
      - "3000:3000"
    environment:
      <<: *common-variables
      MONGO_HOST_IP: db
      DB_URI: mongodb://db
      DB_NAME: testdb

  db:
    image: mongo:3.6.1
    restart: always
    container_name: mongo-db
    volumes: 
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports: 
      - 27017:27017
    command: mongod
    environment:
      <<: *common-variables

networks:
  nesjs-network:
    driver: bridge

volumes:
  mongodb:
  mongodb_config:
